// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationDataTable.Models;

public partial class Citiesofworld
{
    public int Id { get; set; }

    public string Sigla { get; set; }

    public string SiglaCity { get; set; }

    public string SiglaCountry { get; set; }

    public string AirportName { get; set; }

    public string City { get; set; }

    public bool? International { get; set; }

    public int? Priority { get; set; }
}